/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_test(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_test(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_test(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT char * SWIGSTDCALL CSharp_fp_driver_get_name(void * jarg1) {
  char * jresult ;
  struct fp_driver *arg1 = (struct fp_driver *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct fp_driver *)jarg1; 
  result = (char *)fp_driver_get_name(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_fp_driver_get_full_name(void * jarg1) {
  char * jresult ;
  struct fp_driver *arg1 = (struct fp_driver *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct fp_driver *)jarg1; 
  result = (char *)fp_driver_get_full_name(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_driver_get_driver_id(void * jarg1) {
  void * jresult ;
  struct fp_driver *arg1 = (struct fp_driver *) 0 ;
  uint16_t result;
  
  arg1 = (struct fp_driver *)jarg1; 
  result = fp_driver_get_driver_id(arg1);
  {
    uint16_t * resultptr = (uint16_t *) malloc(sizeof(uint16_t));
    memmove(resultptr, &result, sizeof(uint16_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_driver_get_scan_type(void * jarg1) {
  int jresult ;
  struct fp_driver *arg1 = (struct fp_driver *) 0 ;
  enum fp_scan_type result;
  
  arg1 = (struct fp_driver *)jarg1; 
  result = (enum fp_scan_type)fp_driver_get_scan_type(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_discover_devs() {
  void * jresult ;
  struct fp_dscv_dev **result = 0 ;
  
  result = (struct fp_dscv_dev **)fp_discover_devs();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_dscv_devs_free(void * jarg1) {
  struct fp_dscv_dev **arg1 = (struct fp_dscv_dev **) 0 ;
  
  arg1 = (struct fp_dscv_dev **)jarg1; 
  fp_dscv_devs_free(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dscv_dev_get_driver(void * jarg1) {
  void * jresult ;
  struct fp_dscv_dev *arg1 = (struct fp_dscv_dev *) 0 ;
  struct fp_driver *result = 0 ;
  
  arg1 = (struct fp_dscv_dev *)jarg1; 
  result = (struct fp_driver *)fp_dscv_dev_get_driver(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dscv_dev_get_devtype(void * jarg1) {
  void * jresult ;
  struct fp_dscv_dev *arg1 = (struct fp_dscv_dev *) 0 ;
  uint32_t result;
  
  arg1 = (struct fp_dscv_dev *)jarg1; 
  result = fp_dscv_dev_get_devtype(arg1);
  {
    uint32_t * resultptr = (uint32_t *) malloc(sizeof(uint32_t));
    memmove(resultptr, &result, sizeof(uint32_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dscv_dev_supports_print_data(void * jarg1, void * jarg2) {
  int jresult ;
  struct fp_dscv_dev *arg1 = (struct fp_dscv_dev *) 0 ;
  struct fp_print_data *arg2 = (struct fp_print_data *) 0 ;
  int result;
  
  arg1 = (struct fp_dscv_dev *)jarg1; 
  arg2 = (struct fp_print_data *)jarg2; 
  result = (int)fp_dscv_dev_supports_print_data(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dscv_dev_supports_dscv_print(void * jarg1, void * jarg2) {
  int jresult ;
  struct fp_dscv_dev *arg1 = (struct fp_dscv_dev *) 0 ;
  struct fp_dscv_print *arg2 = (struct fp_dscv_print *) 0 ;
  int result;
  
  arg1 = (struct fp_dscv_dev *)jarg1; 
  arg2 = (struct fp_dscv_print *)jarg2; 
  result = (int)fp_dscv_dev_supports_dscv_print(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dscv_dev_for_print_data(void * jarg1, void * jarg2) {
  void * jresult ;
  struct fp_dscv_dev **arg1 = (struct fp_dscv_dev **) 0 ;
  struct fp_print_data *arg2 = (struct fp_print_data *) 0 ;
  struct fp_dscv_dev *result = 0 ;
  
  arg1 = (struct fp_dscv_dev **)jarg1; 
  arg2 = (struct fp_print_data *)jarg2; 
  result = (struct fp_dscv_dev *)fp_dscv_dev_for_print_data(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dscv_dev_for_dscv_print(void * jarg1, void * jarg2) {
  void * jresult ;
  struct fp_dscv_dev **arg1 = (struct fp_dscv_dev **) 0 ;
  struct fp_dscv_print *arg2 = (struct fp_dscv_print *) 0 ;
  struct fp_dscv_dev *result = 0 ;
  
  arg1 = (struct fp_dscv_dev **)jarg1; 
  arg2 = (struct fp_dscv_print *)jarg2; 
  result = (struct fp_dscv_dev *)fp_dscv_dev_for_dscv_print(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dscv_dev_get_driver_id(void * jarg1) {
  void * jresult ;
  struct fp_dscv_dev *arg1 = (struct fp_dscv_dev *) 0 ;
  uint16_t result;
  
  arg1 = (struct fp_dscv_dev *)jarg1; 
  result = fp_dscv_dev_get_driver_id(arg1);
  {
    uint16_t * resultptr = (uint16_t *) malloc(sizeof(uint16_t));
    memmove(resultptr, &result, sizeof(uint16_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_discover_prints() {
  void * jresult ;
  struct fp_dscv_print **result = 0 ;
  
  result = (struct fp_dscv_print **)fp_discover_prints();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_dscv_prints_free(void * jarg1) {
  struct fp_dscv_print **arg1 = (struct fp_dscv_print **) 0 ;
  
  arg1 = (struct fp_dscv_print **)jarg1; 
  fp_dscv_prints_free(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dscv_print_get_driver_id(void * jarg1) {
  void * jresult ;
  struct fp_dscv_print *arg1 = (struct fp_dscv_print *) 0 ;
  uint16_t result;
  
  arg1 = (struct fp_dscv_print *)jarg1; 
  result = fp_dscv_print_get_driver_id(arg1);
  {
    uint16_t * resultptr = (uint16_t *) malloc(sizeof(uint16_t));
    memmove(resultptr, &result, sizeof(uint16_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dscv_print_get_devtype(void * jarg1) {
  void * jresult ;
  struct fp_dscv_print *arg1 = (struct fp_dscv_print *) 0 ;
  uint32_t result;
  
  arg1 = (struct fp_dscv_print *)jarg1; 
  result = fp_dscv_print_get_devtype(arg1);
  {
    uint32_t * resultptr = (uint32_t *) malloc(sizeof(uint32_t));
    memmove(resultptr, &result, sizeof(uint32_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dscv_print_get_finger(void * jarg1) {
  int jresult ;
  struct fp_dscv_print *arg1 = (struct fp_dscv_print *) 0 ;
  enum fp_finger result;
  
  arg1 = (struct fp_dscv_print *)jarg1; 
  result = (enum fp_finger)fp_dscv_print_get_finger(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dscv_print_delete(void * jarg1) {
  int jresult ;
  struct fp_dscv_print *arg1 = (struct fp_dscv_print *) 0 ;
  int result;
  
  arg1 = (struct fp_dscv_print *)jarg1; 
  result = (int)fp_dscv_print_delete(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dev_open(void * jarg1) {
  void * jresult ;
  struct fp_dscv_dev *arg1 = (struct fp_dscv_dev *) 0 ;
  struct fp_dev *result = 0 ;
  
  arg1 = (struct fp_dscv_dev *)jarg1; 
  result = (struct fp_dev *)fp_dev_open(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_dev_close(void * jarg1) {
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  
  arg1 = (struct fp_dev *)jarg1; 
  fp_dev_close(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dev_get_driver(void * jarg1) {
  void * jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_driver *result = 0 ;
  
  arg1 = (struct fp_dev *)jarg1; 
  result = (struct fp_driver *)fp_dev_get_driver(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dev_get_nr_enroll_stages(void * jarg1) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  result = (int)fp_dev_get_nr_enroll_stages(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_dev_get_devtype(void * jarg1) {
  void * jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  uint32_t result;
  
  arg1 = (struct fp_dev *)jarg1; 
  result = fp_dev_get_devtype(arg1);
  {
    uint32_t * resultptr = (uint32_t *) malloc(sizeof(uint32_t));
    memmove(resultptr, &result, sizeof(uint32_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dev_supports_print_data(void * jarg1, void * jarg2) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_print_data *arg2 = (struct fp_print_data *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_print_data *)jarg2; 
  result = (int)fp_dev_supports_print_data(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dev_supports_dscv_print(void * jarg1, void * jarg2) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_dscv_print *arg2 = (struct fp_dscv_print *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_dscv_print *)jarg2; 
  result = (int)fp_dev_supports_dscv_print(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dev_supports_imaging(void * jarg1) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  result = (int)fp_dev_supports_imaging(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dev_img_capture(void * jarg1, int jarg2, void * jarg3) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  int arg2 ;
  struct fp_img **arg3 = (struct fp_img **) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (struct fp_img **)jarg3; 
  result = (int)fp_dev_img_capture(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dev_get_img_width(void * jarg1) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  result = (int)fp_dev_get_img_width(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dev_get_img_height(void * jarg1) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  result = (int)fp_dev_get_img_height(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_enroll_finger_img(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_print_data **arg2 = (struct fp_print_data **) 0 ;
  struct fp_img **arg3 = (struct fp_img **) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_print_data **)jarg2; 
  arg3 = (struct fp_img **)jarg3; 
  result = (int)fp_enroll_finger_img(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_enroll_finger(void * jarg1, void * jarg2) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_print_data **arg2 = (struct fp_print_data **) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_print_data **)jarg2; 
  result = (int)fp_enroll_finger(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_verify_finger_img(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_print_data *arg2 = (struct fp_print_data *) 0 ;
  struct fp_img **arg3 = (struct fp_img **) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_print_data *)jarg2; 
  arg3 = (struct fp_img **)jarg3; 
  result = (int)fp_verify_finger_img(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_verify_finger(void * jarg1, void * jarg2) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_print_data *arg2 = (struct fp_print_data *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_print_data *)jarg2; 
  result = (int)fp_verify_finger(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_dev_supports_identification(void * jarg1) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  result = (int)fp_dev_supports_identification(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_identify_finger_img(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_print_data **arg2 = (struct fp_print_data **) 0 ;
  size_t *arg3 = (size_t *) 0 ;
  struct fp_img **arg4 = (struct fp_img **) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_print_data **)jarg2; 
  arg3 = (size_t *)jarg3; 
  arg4 = (struct fp_img **)jarg4; 
  result = (int)fp_identify_finger_img(arg1,arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_identify_finger(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_print_data **arg2 = (struct fp_print_data **) 0 ;
  size_t *arg3 = (size_t *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_print_data **)jarg2; 
  arg3 = (size_t *)jarg3; 
  result = (int)fp_identify_finger(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_print_data_load(void * jarg1, int jarg2, void * jarg3) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  enum fp_finger arg2 ;
  struct fp_print_data **arg3 = (struct fp_print_data **) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (enum fp_finger)jarg2; 
  arg3 = (struct fp_print_data **)jarg3; 
  result = (int)fp_print_data_load(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_print_data_from_dscv_print(void * jarg1, void * jarg2) {
  int jresult ;
  struct fp_dscv_print *arg1 = (struct fp_dscv_print *) 0 ;
  struct fp_print_data **arg2 = (struct fp_print_data **) 0 ;
  int result;
  
  arg1 = (struct fp_dscv_print *)jarg1; 
  arg2 = (struct fp_print_data **)jarg2; 
  result = (int)fp_print_data_from_dscv_print(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_print_data_save(void * jarg1, int jarg2) {
  int jresult ;
  struct fp_print_data *arg1 = (struct fp_print_data *) 0 ;
  enum fp_finger arg2 ;
  int result;
  
  arg1 = (struct fp_print_data *)jarg1; 
  arg2 = (enum fp_finger)jarg2; 
  result = (int)fp_print_data_save(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_print_data_delete(void * jarg1, int jarg2) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  enum fp_finger arg2 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (enum fp_finger)jarg2; 
  result = (int)fp_print_data_delete(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_print_data_free(void * jarg1) {
  struct fp_print_data *arg1 = (struct fp_print_data *) 0 ;
  
  arg1 = (struct fp_print_data *)jarg1; 
  fp_print_data_free(arg1);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_fp_print_data_get_data(void * jarg1, void * jarg2) {
  unsigned long jresult ;
  struct fp_print_data *arg1 = (struct fp_print_data *) 0 ;
  unsigned char **arg2 = (unsigned char **) 0 ;
  size_t result;
  
  arg1 = (struct fp_print_data *)jarg1; 
  arg2 = (unsigned char **)jarg2; 
  result = fp_print_data_get_data(arg1,arg2);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_print_data_from_data(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  size_t arg2 ;
  struct fp_print_data *result = 0 ;
  
  arg1 = (unsigned char *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (struct fp_print_data *)fp_print_data_from_data(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_print_data_get_driver_id(void * jarg1) {
  void * jresult ;
  struct fp_print_data *arg1 = (struct fp_print_data *) 0 ;
  uint16_t result;
  
  arg1 = (struct fp_print_data *)jarg1; 
  result = fp_print_data_get_driver_id(arg1);
  {
    uint16_t * resultptr = (uint16_t *) malloc(sizeof(uint16_t));
    memmove(resultptr, &result, sizeof(uint16_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_print_data_get_devtype(void * jarg1) {
  void * jresult ;
  struct fp_print_data *arg1 = (struct fp_print_data *) 0 ;
  uint32_t result;
  
  arg1 = (struct fp_print_data *)jarg1; 
  result = fp_print_data_get_devtype(arg1);
  {
    uint32_t * resultptr = (uint32_t *) malloc(sizeof(uint32_t));
    memmove(resultptr, &result, sizeof(uint32_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_x_set(void * jarg1, int jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_minutia_x_get(void * jarg1) {
  int jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int) ((arg1)->x);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_y_set(void * jarg1, int jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_minutia_y_get(void * jarg1) {
  int jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int) ((arg1)->y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_ex_set(void * jarg1, int jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ex = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_minutia_ex_get(void * jarg1) {
  int jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int) ((arg1)->ex);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_ey_set(void * jarg1, int jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ey = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_minutia_ey_get(void * jarg1) {
  int jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int) ((arg1)->ey);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_direction_set(void * jarg1, int jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->direction = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_minutia_direction_get(void * jarg1) {
  int jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int) ((arg1)->direction);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_reliability_set(void * jarg1, double jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  double arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->reliability = arg2;
}


SWIGEXPORT double SWIGSTDCALL CSharp_fp_minutia_reliability_get(void * jarg1) {
  double jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  double result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (double) ((arg1)->reliability);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_type_set(void * jarg1, int jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_minutia_type_get(void * jarg1) {
  int jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int) ((arg1)->type);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_appearing_set(void * jarg1, int jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->appearing = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_minutia_appearing_get(void * jarg1) {
  int jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int) ((arg1)->appearing);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_feature_id_set(void * jarg1, int jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->feature_id = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_minutia_feature_id_get(void * jarg1) {
  int jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int) ((arg1)->feature_id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_nbrs_set(void * jarg1, void * jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int *arg2 = (int *) 0 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int *)jarg2; 
  if (arg1) (arg1)->nbrs = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_minutia_nbrs_get(void * jarg1) {
  void * jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int *result = 0 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int *) ((arg1)->nbrs);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_ridge_counts_set(void * jarg1, void * jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int *arg2 = (int *) 0 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int *)jarg2; 
  if (arg1) (arg1)->ridge_counts = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_minutia_ridge_counts_get(void * jarg1) {
  void * jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int *result = 0 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int *) ((arg1)->ridge_counts);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_minutia_num_nbrs_set(void * jarg1, int jarg2) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->num_nbrs = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_minutia_num_nbrs_get(void * jarg1) {
  int jresult ;
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  int result;
  
  arg1 = (struct fp_minutia *)jarg1; 
  result = (int) ((arg1)->num_nbrs);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_fp_minutia() {
  void * jresult ;
  struct fp_minutia *result = 0 ;
  
  result = (struct fp_minutia *)calloc(1, sizeof(struct fp_minutia));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_fp_minutia(void * jarg1) {
  struct fp_minutia *arg1 = (struct fp_minutia *) 0 ;
  
  arg1 = (struct fp_minutia *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_img_get_height(void * jarg1) {
  int jresult ;
  struct fp_img *arg1 = (struct fp_img *) 0 ;
  int result;
  
  arg1 = (struct fp_img *)jarg1; 
  result = (int)fp_img_get_height(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_img_get_width(void * jarg1) {
  int jresult ;
  struct fp_img *arg1 = (struct fp_img *) 0 ;
  int result;
  
  arg1 = (struct fp_img *)jarg1; 
  result = (int)fp_img_get_width(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_img_get_data(void * jarg1) {
  void * jresult ;
  struct fp_img *arg1 = (struct fp_img *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (struct fp_img *)jarg1; 
  result = (unsigned char *)fp_img_get_data(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_img_save_to_file(void * jarg1, char * jarg2) {
  int jresult ;
  struct fp_img *arg1 = (struct fp_img *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (struct fp_img *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)fp_img_save_to_file(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_img_standardize(void * jarg1) {
  struct fp_img *arg1 = (struct fp_img *) 0 ;
  
  arg1 = (struct fp_img *)jarg1; 
  fp_img_standardize(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_img_binarize(void * jarg1) {
  void * jresult ;
  struct fp_img *arg1 = (struct fp_img *) 0 ;
  struct fp_img *result = 0 ;
  
  arg1 = (struct fp_img *)jarg1; 
  result = (struct fp_img *)fp_img_binarize(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_fp_img_get_minutiae(void * jarg1, void * jarg2) {
  void * jresult ;
  struct fp_img *arg1 = (struct fp_img *) 0 ;
  int *arg2 = (int *) 0 ;
  struct fp_minutia **result = 0 ;
  
  arg1 = (struct fp_img *)jarg1; 
  arg2 = (int *)jarg2; 
  result = (struct fp_minutia **)fp_img_get_minutiae(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_img_free(void * jarg1) {
  struct fp_img *arg1 = (struct fp_img *) 0 ;
  
  arg1 = (struct fp_img *)jarg1; 
  fp_img_free(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_pollfd_fd_set(void * jarg1, int jarg2) {
  struct fp_pollfd *arg1 = (struct fp_pollfd *) 0 ;
  int arg2 ;
  
  arg1 = (struct fp_pollfd *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->fd = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_pollfd_fd_get(void * jarg1) {
  int jresult ;
  struct fp_pollfd *arg1 = (struct fp_pollfd *) 0 ;
  int result;
  
  arg1 = (struct fp_pollfd *)jarg1; 
  result = (int) ((arg1)->fd);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_pollfd_events_set(void * jarg1, short jarg2) {
  struct fp_pollfd *arg1 = (struct fp_pollfd *) 0 ;
  short arg2 ;
  
  arg1 = (struct fp_pollfd *)jarg1; 
  arg2 = (short)jarg2; 
  if (arg1) (arg1)->events = arg2;
}


SWIGEXPORT short SWIGSTDCALL CSharp_fp_pollfd_events_get(void * jarg1) {
  short jresult ;
  struct fp_pollfd *arg1 = (struct fp_pollfd *) 0 ;
  short result;
  
  arg1 = (struct fp_pollfd *)jarg1; 
  result = (short) ((arg1)->events);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_fp_pollfd() {
  void * jresult ;
  struct fp_pollfd *result = 0 ;
  
  result = (struct fp_pollfd *)calloc(1, sizeof(struct fp_pollfd));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_fp_pollfd(void * jarg1) {
  struct fp_pollfd *arg1 = (struct fp_pollfd *) 0 ;
  
  arg1 = (struct fp_pollfd *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_handle_events_timeout(void * jarg1) {
  int jresult ;
  struct timeval *arg1 = (struct timeval *) 0 ;
  int result;
  
  arg1 = (struct timeval *)jarg1; 
  result = (int)fp_handle_events_timeout(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_handle_events() {
  int jresult ;
  int result;
  
  result = (int)fp_handle_events();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_fp_get_pollfds(void * jarg1) {
  unsigned long jresult ;
  struct fp_pollfd **arg1 = (struct fp_pollfd **) 0 ;
  size_t result;
  
  arg1 = (struct fp_pollfd **)jarg1; 
  result = fp_get_pollfds(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_get_next_timeout(void * jarg1) {
  int jresult ;
  struct timeval *arg1 = (struct timeval *) 0 ;
  int result;
  
  arg1 = (struct timeval *)jarg1; 
  result = (int)fp_get_next_timeout(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_set_pollfd_notifiers(void * jarg1, void * jarg2) {
  fp_pollfd_added_cb arg1 = (fp_pollfd_added_cb) 0 ;
  fp_pollfd_removed_cb arg2 = (fp_pollfd_removed_cb) 0 ;
  
  arg1 = (fp_pollfd_added_cb)jarg1; 
  arg2 = (fp_pollfd_removed_cb)jarg2; 
  fp_set_pollfd_notifiers(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_init() {
  int jresult ;
  int result;
  
  result = (int)fp_init();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_exit() {
  fp_exit();
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_set_debug(int jarg1) {
  int arg1 ;
  
  arg1 = (int)jarg1; 
  fp_set_debug(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_async_dev_open(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  struct fp_dscv_dev *arg1 = (struct fp_dscv_dev *) 0 ;
  fp_dev_open_cb arg2 = (fp_dev_open_cb) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  arg1 = (struct fp_dscv_dev *)jarg1; 
  arg2 = (fp_dev_open_cb)jarg2; 
  arg3 = (void *)jarg3; 
  result = (int)fp_async_dev_open(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_fp_async_dev_close(void * jarg1, void * jarg2, void * jarg3) {
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  fp_dev_close_cb arg2 = (fp_dev_close_cb) 0 ;
  void *arg3 = (void *) 0 ;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (fp_dev_close_cb)jarg2; 
  arg3 = (void *)jarg3; 
  fp_async_dev_close(arg1,arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_async_enroll_start(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  fp_enroll_stage_cb arg2 = (fp_enroll_stage_cb) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (fp_enroll_stage_cb)jarg2; 
  arg3 = (void *)jarg3; 
  result = (int)fp_async_enroll_start(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_async_enroll_stop(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  fp_enroll_stop_cb arg2 = (fp_enroll_stop_cb) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (fp_enroll_stop_cb)jarg2; 
  arg3 = (void *)jarg3; 
  result = (int)fp_async_enroll_stop(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_async_verify_start(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_print_data *arg2 = (struct fp_print_data *) 0 ;
  fp_verify_cb arg3 = (fp_verify_cb) 0 ;
  void *arg4 = (void *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_print_data *)jarg2; 
  arg3 = (fp_verify_cb)jarg3; 
  arg4 = (void *)jarg4; 
  result = (int)fp_async_verify_start(arg1,arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_async_verify_stop(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  fp_verify_stop_cb arg2 = (fp_verify_stop_cb) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (fp_verify_stop_cb)jarg2; 
  arg3 = (void *)jarg3; 
  result = (int)fp_async_verify_stop(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_async_identify_start(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  struct fp_print_data **arg2 = (struct fp_print_data **) 0 ;
  fp_identify_cb arg3 = (fp_identify_cb) 0 ;
  void *arg4 = (void *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (struct fp_print_data **)jarg2; 
  arg3 = (fp_identify_cb)jarg3; 
  arg4 = (void *)jarg4; 
  result = (int)fp_async_identify_start(arg1,arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_fp_async_identify_stop(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  struct fp_dev *arg1 = (struct fp_dev *) 0 ;
  fp_identify_stop_cb arg2 = (fp_identify_stop_cb) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  arg1 = (struct fp_dev *)jarg1; 
  arg2 = (fp_identify_stop_cb)jarg2; 
  arg3 = (void *)jarg3; 
  result = (int)fp_async_identify_stop(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

